### ISSUE TITLE
chapter on the side bar 

### ISSUE THREAD

**Issue by tchoi8** [HAWRAF/PoeticComputationReader#1]
Hi

In the current build, when I click on chapter 2 (on the right side bar), it directs me to href="/chapters/ch.2-p.1" which causes a broken link, I think it needs to be  href="/chapters/ch.2"? 

Are chapter links handled in chapter-bundle.html inside of _layouts?  
is it something to do with 		{% assign currentChapter = page.chapter %} ? 

thanks!

**Comment by NickyTesla** [comment]
Yep there was a broken link in the future chapters panel.  Just pushed an edit -- should be resolved
