### ISSUE TITLE
Reference readings 

### ISSUE THREAD

**Issue by tchoi8** [HAWRAF/PoeticComputationReader#3]
![image](https://user-images.githubusercontent.com/683107/30707480-992ad24a-9ec9-11e7-8199-25faefdd67eb.png)
![image](https://user-images.githubusercontent.com/683107/30707517-b531ac48-9ec9-11e7-89a4-6f24d6541d5e.png)

Are the reference readings showing up?

**Comment by HAWRAF** [comment]
Yeah, we changed the syntax in the markdown to reflect one of your earlier suggestions of having a more flexible input type.  Now the all content is pulled from the reference -> body.  There's an example in the chapters directory under chapter 1 + here's a screenshot:

<img width="627" alt="screen shot 2017-09-21 at 12 55 15 pm" src="https://user-images.githubusercontent.com/31791572/30708271-40087e26-9ecc-11e7-8309-92fc713fba17.png">

**Comment by tchoi8** [comment]
Thank you! I'll reflect in the content.

**Comment by HAWRAF** [comment]
Sounds good!
