### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by tchoi8** [HAWRAF/PoeticComputationReader#4]
Hi friends. 

I uploaded the page to http://poeticcomputation.info/  and it's working well.

However I can't get the site to open on my mobile phone. I wonder if you have the same issue? 
If it's helpful to see the code I'm using, I forked the latest build and my current build is uploaded here. https://github.com/tchoi8/PoeticComputationReader

**Comment by HAWRAF** [comment]
Hmmm... this happened the last time the code was bundled and I wonder if it has something to do with that.  Will check now

**Comment by HAWRAF** [comment]
can you try the new bundle.js-  there was a line throwing an err in the console i removed.  if it doesn't work with this new one i'll upload the files and see what's going on

**Comment by HAWRAF** [comment]
did this work?

**Comment by tchoi8** [comment]
Yes, I uploaded the latest build and it works on my mobile. It still gives this error but I'm not sure if it's crucial.
![image](https://user-images.githubusercontent.com/683107/30760937-5e6a06da-9faa-11e7-9176-47bdf4ef4b1c.png)
 I have not yet updated the chapters in the latest build yet, but I think it should be fine. Will let u know via this issue, so can we keep it open for time being? 

Thanks!

**Comment by HAWRAF** [comment]
OK sounds good, it's loading on mine now too.  I'll have a look at that and see what's causing it, one more small update to come.. I'll give u a shout when it's pushed.  Thanks!

**Comment by HAWRAF** [comment]
Just pushed the fix to the "thisFunction" is not defined error.  It's actually crucial that the new bundle.js gets switched in b/c the error blocks the resize handler :0..  

Also can you update the CSS files?  There's a couple small changes - namely a transition on mobile that needs to be in there.  Hopefully the last stuff!  Thanks!
